services:
  database_api:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: game-telemetry-database-api
    ports:
      - "10101:10101"
    volumes:
      - ./database:/app
    environment:
      - DATABASE_URL=sqlite:///./td.db
  
  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    container_name: game-telemetry-dashboard
    ports:
      - "10102:10102"
    volumes:
      - ./dashboard:/app/dashboard
    environment:
      - API_URL=http://database_api:10101
    depends_on:
      - database_api
    
  game:
    build:
      context: ./game
      dockerfile: Dockerfile
    container_name: game-telemetry-game
    ports:
      - "10103:10103"
    volumes:
      - ./game:/app