services:
  database_api:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: game-telemetry-database-api
    ports:
      - "10101:10101"
    volumes:
      - ./database:/app
    env_file:
      - .env
  
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: game-telemetry-dashboard
    ports:
      - "10102:10102"
    volumes:
      - ./dashboard:/app
    environment:
      - API_URL=http://database_api:10101
    depends_on:
      - database_api